## Two-dimensional arrays

Two-dimensional arrays are very useful for arranging data in many engineering applications and for performing mathematical operations. Commonly, 2D arrays are used to represents matrices. To create the matrix

$$
A = 
\begin{bmatrix} 
2.2 & 3.7 & 9.1\\ 
-4 & 3.1 & 1.3
\end{bmatrix} 
$$

we use:

In [2]:
import numpy as np

A = 

[[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]


If we check the length of `A`:

2


it reports the number of rows. To get the shape of the array, we use:

(2, 3)


which reports 2 rows and 3 columns (stored using a tuple). To get the number of rows and the number of columns,

In [4]:
num_rows = 
num_cols = 


Number of rows is 2, number of columns is 3.


We can 'index' into a 2D array using two indices, the first for the row index and the second for the column index:

In [5]:
A02 = 

A01 = 


9.1
3.7


With `A[0]` and `A[1]`, we will get the first and second rows, respectively:

[2.2 3.7 9.1]
[-4.   3.1  1.3]


### Transpose a matrix:

$$
A = 
\begin{bmatrix} 
2.2 & 3.7 & 9.1\\ 
-4 & 3.1 & 1.3
\end{bmatrix} 
$$


to 

$$
A^T = 
\begin{bmatrix} 
2.2 & -4\\ 
3.7 & 3.1 \\
9.1 & 1.3
\end{bmatrix} 
$$


In [7]:
A = 


A= [[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]



In [8]:
At = 


Transpose of A= [[ 2.2 -4. ]
 [ 3.7  3.1]
 [ 9.1  1.3]]



### 2D array (matrix) operations

For those who have seen matrices previously, the operations in this section will be familiar. For those who have not encountered matrices, you might want to revisit this section once matrices have been covered in the mathematics lectures.

#### Matrix-vector and matrix-matrix multiplication

We will consider the matrix $A$:

$$
A  = 
\begin{bmatrix}
3 & 2 \\
1 & 4
\end{bmatrix}
$$

and the vector $x$:

$$
x  = 
\begin{bmatrix}
2 \\ -1
\end{bmatrix}
$$

In [9]:
A = 

x = 


Matrix A:
 [[3 2]
 [1 4]]
Vector x:
 [ 2 -1]


Doing it manually

(2, 2)
(2,)


We can compute the matrix-vector product $y = Ax$ by:

In [11]:
y = 


[ 4 -2]


### Matrix-matrix multiplication  

Computing $C = AB$, where $A$, $B$, and $C$ are all matrices, the approach is similar:

In [12]:
B = 

C = 

[[3.9 4. ]
 [1.3 8. ]]


The inverse of a matrix ($A^{-1}$) and the determinant ($\det(A)$) can be computed using functions in the NumPy submodule `linalg`:

In [13]:
Ainv = 

Adet = 


Inverse of A:
 [[ 0.4 -0.2]
 [-0.1  0.3]]
Determinant of A: 10.000000000000002


## Cross product

![Cross product](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cross_parallelogram.png/685px-Cross_parallelogram.png)

In [14]:
a = 
b = 

c = 


[-3  6 -3]


NumPy is large library, so it uses sub-modules to arrange functionality.

A very common matrix is the *identity matrix* $I$. We can create a $4 \times 4$ identity matrix using:

In [15]:
I = 


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Solve a linear system of equations

Consider a Matrix $A$, and vectors $x$ and $b$:

$$ 
\begin{bmatrix} 
4 & 1 & 2 \\
3 & 5 & 1 \\
1 & 1 & 3 \\
\end{bmatrix} 
	\begin{bmatrix}
		x_1\\
		x_2\\
		x_3\\
	\end{bmatrix}
    =
	\begin{bmatrix}
		4 \\
		7 \\
		3 \\
	\end{bmatrix}
$$

we use:

In [4]:
A = 
b = 

Check the length of `A` and `b`

(3, 3)
(3,)


The determinant ($\det(A)$) can be computed using functions in the NumPy submodule `linalg`. If the determinant of $A$ is non-zero, then we have a solution.

In [5]:
Adet = 


Determinant of A: 44.000000000000014


Solve using the inverse of A

In [6]:
Ainv = 


x = [0.5 1.  0.5]


## Solution using Gauss Elimination direct approach

In [8]:
A = 

b = 

x = 


x = [0.5 1.  0.5]


### Gauss Elimination: Limitations

(1) Prone to round off errors, when we have many (> 100) equations.

(2) If coeffcient matrix is sparse (lots of zeros), elimination methods are very ineffcient.

There are other direct approaches such as Gauss-Jordan Elimination and LU decomposition.

Alternatively, it can be solved iteratively.

## Solution using Gauss-Seidel Iterative approach

For conciseness, we limit to 3 x 3 equations. If diagonal elements are all non-zero, then the equations can be solved as:

$$
\begin{bmatrix} 
a_{11} & a_{12} & a_{13} \\ 
a_{21} & a_{22} & a_{23} \\ 
a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
    \begin{bmatrix}
		x_1\\
		x_2\\
		x_3\\
	\end{bmatrix}
	\begin{bmatrix}
		b_1 \\
		b_2 \\
		b_3 \\
	\end{bmatrix}
$$
$$
x_1 = \frac{b_1 - a_{12}x_2-a_{13}x_3}{a_{11}}
$$
$$
x_2 = \frac{b_2 - a_{21}x_1-a_{23}x_3}{a_{22}}
$$
$$
x_3 = \frac{b_3 - a_{31}x_1-a_{32}x_2}{a_{33}}
$$


For a given initial $(x_{1}^{n}, x_{2}^{n}, x_{3}^{n})$, the above equation can be used for computed updated $(x_{1}^{n+1}, x_{2}^{n+1}, x_{3}^{n+1}$).

$$
x_{1}^{n+1} = \frac{b_1 - a_{12}x_{2}^{n}-a_{13}x_{3}^{n}}{a_{11}} \hookleftarrow
$$
$$
x_{2}^{n+1} = \frac{b_2 - a_{21}x_{1}^{n+1}-a_{23}x_{3}^{n}}{a_{22}} \hookleftarrow
$$
$$
x_{3}^{n+1} = \frac{b_3 - a_{31}x_{1}^{n+1}-a_{32}x_{2}^{n+1}}{a_{33}}
$$

Using Gauss-Seidel solve for [x]

$$ 
\begin{bmatrix} 
4 & 1 & 2 \\
3 & 5 & 1 \\
1 & 1 & 3 \\
\end{bmatrix} 
	\begin{bmatrix}
		x_1\\
		x_2\\
		x_3\\
	\end{bmatrix}
    =
	\begin{bmatrix}
		4 \\
		7 \\
		3 \\
	\end{bmatrix}
$$

Assuming an initial guess of $x_1; x_2; x_3$ = 0. End of first iteration.

$$
x_{1} = \frac{4 - 1\times0 - 2\times0}{4} = 1 \hookleftarrow
$$
$$
x_{2} = \frac{7 - 3\times1 - 1\times0}{5} = 0.8 \hookleftarrow
$$
$$
x_{3} = \frac{3 - 1\times1 - 1\times0.8}{3} = 0.4
$$

Convergence can be checked using the relative error.

$$
|\epsilon_i| = |\frac{x_i^k - x_i^{k+1}}{x_i^k} \times 100\%|<\epsilon_{tolerance}
$$
where k, and k + 1 represents the current and previous iterations.

Note that Gauss-Seidel only works for diagonally dominant matrix.

In [9]:
import numpy as np

# Gauss-Seidel iterative solver
def gauss_seidel(A, b, x, max_iterations = 1000, tol=1.0E-15):
    # Number of rows
    nrows = np.shape(A)[0]
    # Check size of matrices A and vector b
    if np.shape(A)[0] != np.shape(A)[1] or np.shape(A)[0] != np.shape(b)[0]:
        print("Invalid dimensions")
    
    # Initialize previous iteration to zero
    xprev = np.zeros(nrows)

    # Gauss seidel iterative solver
    for i in range(max_iterations):
        xprev = x.copy()
        for j in range(nrows):
            sum = 0.0
            for k in range(nrows):
                if (k != j):
                    sum = sum + A[j][k] * x[k]
            x[j] = (b[j] - sum) / A[j][j]

        # Calculate norm
        diff_norm = 0.0
        old_norm = 0.0
        for j in range(nrows):
            diff_norm = diff_norm + abs(x[j] - xprev[j])
            old_norm = old_norm + abs(xprev[j])  
        if old_norm == 0.0:
            old_norm = 1.0
        norm = diff_norm / old_norm
        if (norm < tol) and i != 0:
            print("\nGauss-Seidel coverged! x = {}, # of iterations: {} with an error of {}".format(x, i+1, norm))
            return
    print("Doesn't converge.")

# Example of a 3D matrix
matrixA = 
vectorb = 
guess = 

gauss_seidel(matrixA, vectorb, guess)

# 2D Matrices example
matrix2 = 
vector2 = 
guess2 = 

gauss_seidel(matrix2, vector2, guess2, max_iterations=10, tol=1e-5)


Gauss-Seidel coverged! x = [0.5 1.  0.5], # of iterations: 23 with an error of 7.216449660063516e-16

Gauss-Seidel coverged! x = [1.3125006664270664, 1.0624997778576446], # of iterations: 7 with an error of 2.993070908873758e-06
